project:
  type: book

book:
  title: "Mathematics of Data Science"
  author: "Jason R. Wilson"
  chapters:
    - index.qmd
    - part: "1 Linear Systems and Matrices"
      chapters:
        - chapter1/section1_intro_linear_systems.qmd
#        - chapter1/section2_intro_matrices_vectors.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  code-fold: true


